@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> AsyncFile: new
AsyncFile -> Reactor: register event source
Executor -> AsyncFile: poll
User -> AsyncFile: drop
AsyncFile -> Reactor: unregister event source


@enduml